HolidayCalendar/Controllers/HolidayController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HolidayCalendarService;

namespace HolidayCalendar.Controllers
{
    public class HolidayController : Controller
    {
        private HolidayCalendarDbContext db = new HolidayCalendarDbContext();

        // GET: /Holiday/
        [Authorize(Roles="admin")]
        public ActionResult Index()
        {
            return View(Holiday.GetAll());
        }

        // GET: /Holiday/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Holiday/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create([Bind(Include="id,date,repeat_anual,title,is_deleted")] Holiday holiday)
        {
            if (ModelState.IsValid)
            {
                db.Holidays.Add(holiday);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(holiday);
        }

        // GET: /Holiday/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Holiday holiday = db.Holidays.Find(id);
            if (holiday == null)
            {
                return HttpNotFound();
            }
            return View(holiday);
        }

        // POST: /Holiday/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include="id,date,repeat_anual,title,is_deleted")] Holiday holiday)
        {
            if (ModelState.IsValid)
            {
                db.Entry(holiday).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(holiday);
        }

        // GET: /Holiday/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Holiday holiday = db.Holidays.Find(id);
            if (holiday == null)
            {
                return HttpNotFound();
            }
            return View(holiday);
        }

        // POST: /Holiday/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Holiday.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    
    
    }
}

HolidayCalendar/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HolidayCalendar.Controllers
{
    public class ReportController : Controller
    {

        [Authorize(Roles="admin")]
        public ActionResult YearOverview(int? year)
        {
            ViewBag.Year = year ?? DateTime.Now.Year;
            return View(HolidayCalendarService.User.GetAll());
        }
	}
}

HolidayCalendar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/fullcalendar-styles")
    <script src='@Url.Content("~/Scripts/jquery.validate.js")' type='text/javascript'></script>
    <script src='@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")' type='text/javascript'></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Holiday Calendar", "Calendar", "VacationLeave", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if(User.IsInRole("admin")) {
                        <li>@Html.ActionLink("Approve", "Approve", "VacationLeave")</li>
                        <li>@Html.ActionLink("Users", "Index", "User")</li>
                        <li>@Html.ActionLink("Public Holidays", "Index", "Holiday")</li>
                        <li>@Html.ActionLink("Year Overview", "YearOverview", "Report")</li>
                    }
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    @if(User.Identity.IsAuthenticated) {
                        <li>@Html.ActionLink("Logout", "Logout", "User")</li>  
                    }                  
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="content">
            @RenderBody()
        </div>
        <hr />
        <!--<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>-->
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Content/fullcalendar-scripts")

    <script>
        $(function() {

            $(".datepicker").each(function() {
                var el = $(this);
                var params = {
                    format: 'dd M yyyy',
                    autoclose: true
                };
                var startDate = el.data('start-date');

                if(startDate) {
                    params.startDate = startDate == 'today' ? new Date() : startDate;
                }

                el.datepicker(params);
            });
        });
    </script>
    @RenderSection("scripts", required: false)
    
</body>
</html>